# global:
#   namespace: default
#   secretStoreRef:
#     name: "cluster-secret-store"
#     kind: ClusterSecretStore

# externalSecrets:
#   - name: tiktoken-test-credentials
#     # target:
#     #   name: tiktoken-test-secret
#     #   creationPolicy: Owner
#     dataFrom:
#       - extractKey: "tiktoken-config"  

basic-app:
  # appName: host-agent   # cluster set this value at runtime
  serviceAccount: 
    create: false 
    # name: mcp-poc  # cluster set this value at runtime

  replicaCount: 1

  # image: 042889969014.dkr.ecr.us-east-1.amazonaws.com/host_agent:20250909181710   # this value will come from application repo
  imagePullPolicy: IfNotPresent

  ports:
  - name: http
    servicePort: 8000
    containerPort: 8000

  envFrom:
    - secretRef:
        name: unified-db-config-secret
    - secretRef:
        name: tiktoken-config-secret
    - secretRef:
        name: keycloak-config-secret
    - secretRef:
        name: aes-encryption-key-secret
    - secretRef:
        name: redis-config-secret
  env:
    - name: "BATCH_SIZE"
      value: "1"
    - name: "BATCH_TIMEOUT_SECONDS"
      value: "5"

  resources:
    requests:
      cpu: "100m"                # Minimum CPU guaranteed
      memory: "1024Mi"            # Minimum memory guaranteed
    limits:
      cpu: "2000m"                # Max CPU allowed
      memory: "4096Mi"            # Max memory allowed

  ingress:
    enabled: true
    hostname:
      appdomain: kafka-consumer
      # domain: prod.yashtechai.link   # cluster set this value at runtime
    servicePort: 8000
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "500m"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800"
    tls: true
    paths:
      - path: /
        pathType: Prefix

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 90
    targetMemoryUtilizationPercentage: 90


  livenessProbe: {}
    # httpGet:
    #   path: /
    #   port: http
    # initialDelaySeconds: 10
    # periodSeconds: 5

  readinessProbe: {}
    # httpGet:
    #   path: /
    #   port: http
    # initialDelaySeconds: 5
    # periodSeconds: 3

  podSecurityContext: {}
  securityContext: {}

  imagePullSecrets: []
  nodeSelector: {}
  affinity: {}
  tolerations: []
