# global:
#   namespace: default
#   secretStoreRef:
#     name: "cluster-secret-store"
#     kind: ClusterSecretStore

# externalSecrets:
#   - name: tiktoken-test-credentials
#     # target:
#     #   name: tiktoken-test-secret
#     #   creationPolicy: Owner
#     dataFrom:
#       - extractKey: "tiktoken-config"  

basic-app:
  # appName: host-agent   # cluster set this value at runtime
  serviceAccount: 
    create: false 
    # name: mcp-poc  # cluster set this value at runtime

  replicaCount: 1

  # image: 042889969014.dkr.ecr.us-east-1.amazonaws.com/host_agent:20250909181710   # this value will come from application repo
  imagePullPolicy: IfNotPresent

  ports:
  - name: http
    servicePort: 8000
    containerPort: 8000

  envFrom:
    - secretRef:
        name: gemini-config-secret
    - secretRef:
        name: azure-openai-config-secret
    - secretRef:
        name: tiktoken-config-secret
    - secretRef:
        name: keycloak-config-secret
    - secretRef:
        name: otel-config-secret
  env:
    - name: "PORT"
      value: "8000"
    - name: "KEYCLOAK_CLIENT_ID"
      value: "unified_a2a_app"
    - name: "KEYCLOAK_ADMIN_CLIENT_ID"
      value: "unified_a2a_admin_app"
    - name: "GEMINI_MODEL"
      value: "gemini-2.5-flash"
    - name: "MODEL_PROVIDER"
      value: "gemini"
    - name: "HOST_AGENT_NAME"
      value: "PROMPT_ENHANCER"
    - name: "SERVER_NAME"
      value: "PROMPT_ENHANCER"
    - name: "AGENT_NAME"
      value: "PROMPT_ENHANCER_AGENT"
    - name: "AGENT_NAME_CONSTANT"
      value: "PROMPT_ENHANCER_AGENT"
    - name: "OPENAI_MODEL"
      value: "gpt-4o-mini"

  resources:
    requests:
      cpu: "10m"                # Minimum CPU guaranteed
      memory: "400Mi"            # Minimum memory guaranteed
    limits:
      cpu: "50m"                # Max CPU allowed
      memory: "10240Mi"            # Max memory allowed

  ingress:
    enabled: true
    hostname:
      appdomain: prompt-enhancer
      # domain: prod.yashtechai.link   # cluster set this value at runtime
    servicePort: 8000
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "500m"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800"
    tls: true
    paths:
      - path: /
        pathType: Prefix

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 75
    targetMemoryUtilizationPercentage: 80


  livenessProbe: {}
    # httpGet:
    #   path: /
    #   port: http
    # initialDelaySeconds: 10
    # periodSeconds: 5

  readinessProbe: {}
    # httpGet:
    #   path: /
    #   port: http
    # initialDelaySeconds: 5
    # periodSeconds: 3

  podSecurityContext: {}
  securityContext: {}

  imagePullSecrets: []
  nodeSelector: {}
  affinity: {}
  tolerations: []