# global:
#   namespace: default
#   secretStoreRef:
#     name: "cluster-secret-store"
#     kind: ClusterSecretStore

# externalSecrets:
#   - name: tiktoken-test-credentials
#     # target:
#     #   name: tiktoken-test-secret
#     #   creationPolicy: Owner
#     dataFrom:
#       - extractKey: "tiktoken-config"  

basic-app:
  # appName: host-agent   # cluster set this value at runtime
  serviceAccount: 
    create: false 
    # name: mcp-poc  # cluster set this value at runtime

  replicaCount: 1

  # image: 042889969014.dkr.ecr.us-east-1.amazonaws.com/host_agent:20250909181710   # this value will come from application repo
  imagePullPolicy: IfNotPresent

  ports:
  - name: http
    servicePort: 3000
    containerPort: 3000
  - name: grafana-svc
    servicePort: 3000
    containerPort: 3000

  envFrom:
    - secretRef:
        name: aws-otel-grafana-config-secret
    - secretRef:
        name: grafana-database-config-secret
    - secretRef:
        name: grafana-azure-config-secret
  env:
    - name: "GF_DATABASE_TYPE"
      value: "postgres"
    - name: "GF_DATABASE_SSL_MODE"
      value: "require"
    # - name: "GF_SERVER_ROOT_URL"
    #   value: "https://grafana.aifirstenterprise.ai"
    - name: "GF_INSTALL_PLUGINS"
      value: "grafana-x-ray-datasource"

  resources:
    requests:
      cpu: "30m"                # Minimum CPU guaranteed
      memory: "300Mi"            # Minimum memory guaranteed
    limits:
      cpu: "60m"                # Max CPU allowed
      memory: "2048Mi"            # Max memory allowed

  ingress:
    enabled: true
    hostname:
      appdomain: grafana
      # domain: prod.yashtechai.link   # cluster set this value at runtime
    servicePort: 3000
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "500m"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    tls: true
    paths:
      - path: /
        pathType: Prefix

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 90
    targetMemoryUtilizationPercentage: 90


  livenessProbe: {}
    # httpGet:
    #   path: /
    #   port: http
    # initialDelaySeconds: 10
    # periodSeconds: 5

  readinessProbe: {}
    # httpGet:
    #   path: /
    #   port: http
    # initialDelaySeconds: 5
    # periodSeconds: 3

  podSecurityContext: {}
  securityContext: {}

  imagePullSecrets: []
  nodeSelector: {}
  affinity: {}
  tolerations: []
